const arabaStogu = [
  {
    name: 'Maruti 800 AC',
    year: 2007,
    selling_price: 60000,
    km_driven: 70000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Wagon R LXI Minor',
    year: 2007,
    selling_price: 135000,
    km_driven: 50000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Verna 1.6 SX',
    year: 2012,
    selling_price: 600000,
    km_driven: 100000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Datsun RediGO T Option',
    year: 2017,
    selling_price: 250000,
    km_driven: 46000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda Amaze VX i-DTEC',
    year: 2014,
    selling_price: 450000,
    km_driven: 141000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti Alto LX BSIII',
    year: 2007,
    selling_price: 140000,
    km_driven: 125000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Xcent 1.2 Kappa S',
    year: 2016,
    selling_price: 550000,
    km_driven: 25000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Indigo Grand Benzin',
    year: 2014,
    selling_price: 240000,
    km_driven: 60000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai Creta 1.6 VTVT S',
    year: 2015,
    selling_price: 850000,
    km_driven: 25000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Celerio Green VXI',
    year: 2017,
    selling_price: 365000,
    km_driven: 78000,
    fuel: 'CNG',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Chevrolet Sail 1.2 Base',
    year: 2015,
    selling_price: 260000,
    km_driven: 35000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Indigo Grand Benzin',
    year: 2014,
    selling_price: 250000,
    km_driven: 100000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Toyota Corolla Altis 1.8 VL CVT',
    year: 2018,
    selling_price: 1650000,
    km_driven: 25000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti 800 AC',
    year: 2007,
    selling_price: 60000,
    km_driven: 70000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Wagon R LXI Minor',
    year: 2007,
    selling_price: 135000,
    km_driven: 50000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Verna 1.6 SX',
    year: 2012,
    selling_price: 600000,
    km_driven: 100000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Datsun RediGO T Option',
    year: 2017,
    selling_price: 250000,
    km_driven: 46000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda Amaze VX i-DTEC',
    year: 2014,
    selling_price: 450000,
    km_driven: 141000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti Alto LX BSIII',
    year: 2007,
    selling_price: 140000,
    km_driven: 125000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Xcent 1.2 Kappa S',
    year: 2016,
    selling_price: 550000,
    km_driven: 25000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Indigo Grand Benzin',
    year: 2014,
    selling_price: 240000,
    km_driven: 60000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai Creta 1.6 VTVT S',
    year: 2015,
    selling_price: 850000,
    km_driven: 25000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Celerio Green VXI',
    year: 2017,
    selling_price: 365000,
    km_driven: 78000,
    fuel: 'CNG',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Chevrolet Sail 1.2 Base',
    year: 2015,
    selling_price: 260000,
    km_driven: 35000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Indigo Grand Benzin',
    year: 2014,
    selling_price: 250000,
    km_driven: 100000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Toyota Corolla Altis 1.8 VL CVT',
    year: 2018,
    selling_price: 1650000,
    km_driven: 25000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Ciaz VXi Plus',
    year: 2015,
    selling_price: 585000,
    km_driven: 24000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Venue SX Opt Dizel',
    year: 2019,
    selling_price: 1195000,
    km_driven: 5000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Chevrolet Enjoy TCDi LTZ 7 Seater',
    year: 2013,
    selling_price: 390000,
    km_driven: 33000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Jaguar XF 2.2 Litre Luxury',
    year: 2014,
    selling_price: 1964999,
    km_driven: 28000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mercedes-Benz New C-Class 220 CDI AT',
    year: 2013,
    selling_price: 1425000,
    km_driven: 59000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Vitara Brezza ZDi Plus AMT',
    year: 2018,
    selling_price: 975000,
    km_driven: 4500,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Audi Q5 2.0 TDI',
    year: 2011,
    selling_price: 1190000,
    km_driven: 175900,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda City V MT',
    year: 2018,
    selling_price: 930000,
    km_driven: 14500,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Tigor 1.2 Revotron XT',
    year: 2018,
    selling_price: 525000,
    km_driven: 15000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Audi A6 2.0 TDI  Design Edition',
    year: 2013,
    selling_price: 1735000,
    km_driven: 50000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mercedes-Benz New C-Class C 220 CDI Avantgarde',
    year: 2012,
    selling_price: 1375000,
    km_driven: 33800,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Skoda Superb Ambition 2.0 TDI CR AT',
    year: 2011,
    selling_price: 450000,
    km_driven: 130400,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Toyota Corolla Altis G AT',
    year: 2016,
    selling_price: 900000,
    km_driven: 50000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Toyota Innova 2.5 G (Dizel) 7 Seater',
    year: 2015,
    selling_price: 1300000,
    km_driven: 80000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Jeep Compass 1.4 Sport Plus BSIV',
    year: 2019,
    selling_price: 1400000,
    km_driven: 10000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mercedes-Benz E-Class E 200 CGI Elegance',
    year: 2010,
    selling_price: 850000,
    km_driven: 119000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai i10 Magna 1.1L',
    year: 2014,
    selling_price: 229999,
    km_driven: 60000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Dördüncü veya Daha Fazla Sahibi',
  },
  {
    name: 'BMW 3 Series 320d Sport Line',
    year: 2013,
    selling_price: 1550000,
    km_driven: 75800,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Audi Q7 35 TDI Quattro Premium',
    year: 2009,
    selling_price: 1250000,
    km_driven: 78000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'Üçüncü Sahibi',
  },
  {
    name: 'Hyundai Elantra CRDi S',
    year: 2012,
    selling_price: 625000,
    km_driven: 40000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mahindra Scorpio 1.99 S10',
    year: 2014,
    selling_price: 1050000,
    km_driven: 50000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda City i DTEC V',
    year: 2014,
    selling_price: 560000,
    km_driven: 74000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti Wagon R VXI BS IV with ABS',
    year: 2014,
    selling_price: 290000,
    km_driven: 64000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti Wagon R VXI BS IV',
    year: 2012,
    selling_price: 275000,
    km_driven: 60000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Mahindra Scorpio LX',
    year: 2009,
    selling_price: 411000,
    km_driven: 120000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai Santro Xing GLS',
    year: 2009,
    selling_price: 150000,
    km_driven: 79000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Üçüncü Sahibi',
  },
  {
    name: 'Hyundai Grand i10 1.2 Kappa Asta',
    year: 2019,
    selling_price: 500000,
    km_driven: 15000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Alto LXi',
    year: 2006,
    selling_price: 100000,
    km_driven: 80000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Swift Dzire VDI Optional',
    year: 2017,
    selling_price: 725000,
    km_driven: 18500,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Eeco 5 Seater AC BSIV',
    year: 2018,
    selling_price: 401000,
    km_driven: 10200,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai i20 Sportz 1.4 CRDi',
    year: 2018,
    selling_price: 750000,
    km_driven: 29000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Omni Maruti Omni MPI STD BSIII 5-STR W/ IMMOBILISER',
    year: 2018,
    selling_price: 310000,
    km_driven: 28000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Swift ZDi BSIV',
    year: 2016,
    selling_price: 665000,
    km_driven: 46000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai i20 2015-2017 Sportz Option 1.4 CRDi',
    year: 2014,
    selling_price: 465000,
    km_driven: 70000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Alto LXi',
    year: 2012,
    selling_price: 160000,
    km_driven: 60000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Mahindra Jeep CL 500 MDI',
    year: 1996,
    selling_price: 250000,
    km_driven: 35000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Honda City i DTEC VX',
    year: 2014,
    selling_price: 675000,
    km_driven: 90000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Wagon R VXI BS IV',
    year: 2013,
    selling_price: 300000,
    km_driven: 80000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Indica DLS',
    year: 2005,
    selling_price: 70000,
    km_driven: 80000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai EON Magna Plus',
    year: 2014,
    selling_price: 240000,
    km_driven: 73300,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Toyota Etios GD',
    year: 2014,
    selling_price: 525000,
    km_driven: 92000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Alto LXi',
    year: 2009,
    selling_price: 151000,
    km_driven: 66764,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti Alto LXi',
    year: 2009,
    selling_price: 140000,
    km_driven: 100000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Chevrolet Tavera Neo LS B3 - 7(C) seats BSIII',
    year: 2010,
    selling_price: 280000,
    km_driven: 350000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Toyota Corolla Altis Dizel D4DG',
    year: 2011,
    selling_price: 350000,
    km_driven: 230000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mahindra Scorpio 1.99 S6 Plus',
    year: 2017,
    selling_price: 570000,
    km_driven: 60000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai EON Magna Plus',
    year: 2018,
    selling_price: 300000,
    km_driven: 31000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Indigo Classic Dicor',
    year: 2007,
    selling_price: 100000,
    km_driven: 39000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Toyota Innova 2.5 V Dizel 8-seater',
    year: 2009,
    selling_price: 500000,
    km_driven: 120000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Üçüncü Sahibi',
  },
  {
    name: 'Tata Indica Vista Quadrajet LS',
    year: 2014,
    selling_price: 125000,
    km_driven: 166000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Dördüncü veya Daha Fazla Sahibi',
  },
  {
    name: 'Maruti Swift 1.3 VXi',
    year: 2006,
    selling_price: 130000,
    km_driven: 110000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Üçüncü Sahibi',
  },
  {
    name: 'Ford EcoSport 1.5 Dizel Titanium BSIV',
    year: 2017,
    selling_price: 925000,
    km_driven: 35000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Ciaz 1.3 Delta',
    year: 2018,
    selling_price: 750000,
    km_driven: 60000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda Civic 1.8 V AT',
    year: 2007,
    selling_price: 200000,
    km_driven: 54000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Otomatik',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai i10 Sportz 1.2',
    year: 2010,
    selling_price: 248000,
    km_driven: 63000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Skoda Rapid 1.5 TDI Elegance',
    year: 2014,
    selling_price: 450000,
    km_driven: 120000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai Getz GLS',
    year: 2005,
    selling_price: 80000,
    km_driven: 120000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Üçüncü Sahibi',
  },
  {
    name: 'Nissan Terrano XL',
    year: 2014,
    selling_price: 650000,
    km_driven: 76000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai Grand i10 CRDi Sportz',
    year: 2015,
    selling_price: 450000,
    km_driven: 80000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Elite i20 Dizel Era',
    year: 2019,
    selling_price: 650000,
    km_driven: 25000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda Amaze S i-VTEC',
    year: 2016,
    selling_price: 495000,
    km_driven: 11958,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda Brio S MT',
    year: 2015,
    selling_price: 371000,
    km_driven: 20000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Creta 1.6 SX Option',
    year: 2017,
    selling_price: 1025000,
    km_driven: 9000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mercedes-Benz S-Class S 350d Connoisseurs Edition',
    year: 2017,
    selling_price: 8150000,
    km_driven: 6500,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mahindra XUV500 W8 2WD',
    year: 2015,
    selling_price: 750000,
    km_driven: 70000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Renault Duster 85PS Dizel RxL Optional',
    year: 2013,
    selling_price: 600000,
    km_driven: 120000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Santro Xing XO',
    year: 2007,
    selling_price: 80000,
    km_driven: 58000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Mahindra Bolero 2011-2019 SLE',
    year: 2013,
    selling_price: 325000,
    km_driven: 62200,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Audi A6 2.0 TDI Premium Plus',
    year: 2014,
    selling_price: 1470000,
    km_driven: 34000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Fiat Avventura MULTIJET Emotion',
    year: 2015,
    selling_price: 350000,
    km_driven: 53000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Audi A8 4.2 TDI',
    year: 2013,
    selling_price: 2800000,
    km_driven: 49000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Datsun RediGO 1.0 S',
    year: 2017,
    selling_price: 210000,
    km_driven: 15000,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Volkswagen Jetta 1.4 TSI Comfortline',
    year: 2013,
    selling_price: 450000,
    km_driven: 50000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Audi A4 2.0 TDI 177 Bhp Premium Plus',
    year: 2013,
    selling_price: 1150000,
    km_driven: 53000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Honda Civic 1.8 V AT',
    year: 2009,
    selling_price: 210000,
    km_driven: 63500,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mercedes-Benz E-Class Exclusive E 200 BSIV',
    year: 2018,
    selling_price: 4500000,
    km_driven: 9800,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'BMW X1 sDrive 20d xLine',
    year: 2017,
    selling_price: 2750000,
    km_driven: 13000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Volvo V40 D3 R Design',
    year: 2018,
    selling_price: 1975000,
    km_driven: 21000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti SX4 Zxi BSIII',
    year: 2008,
    selling_price: 175000,
    km_driven: 29173,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'BMW 7 Series 730Ld',
    year: 2012,
    selling_price: 2500000,
    km_driven: 48000,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mahindra Bolero Power Plus SLX',
    year: 2017,
    selling_price: 628000,
    km_driven: 120000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Sonata CRDi M/T',
    year: 2010,
    selling_price: 600000,
    km_driven: 100000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Nissan Micra Active XV Benzin',
    year: 2017,
    selling_price: 399000,
    km_driven: 30000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mahindra Xylo D4',
    year: 2018,
    selling_price: 750000,
    km_driven: 87000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Elite i20 Sportz Plus Dual Tone BSIV',
    year: 2019,
    selling_price: 750000,
    km_driven: 15000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Renault KWID RXT',
    year: 2017,
    selling_price: 315000,
    km_driven: 16000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mahindra Xylo E4 BS III',
    year: 2012,
    selling_price: 600000,
    km_driven: 60000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Wagon R LXI Minor',
    year: 2010,
    selling_price: 100000,
    km_driven: 60000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Dördüncü veya Daha Fazla Sahibi',
  },
  {
    name: 'Maruti SX4 ZXI MT BSIV',
    year: 2011,
    selling_price: 250000,
    km_driven: 110000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Üçüncü Sahibi',
  },
  {
    name: 'Renault KWID RXT',
    year: 2017,
    selling_price: 350000,
    km_driven: 25000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai Creta 1.4 CRDi S',
    year: 2016,
    selling_price: 780000,
    km_driven: 60000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Swift Dzire VDI',
    year: 2014,
    selling_price: 434000,
    km_driven: 79350,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai Verna 1.6 VTVT AT S Option',
    year: 2016,
    selling_price: 690000,
    km_driven: 80000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Otomatik',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Mahindra Scorpio LX BSIV',
    year: 2014,
    selling_price: 555000,
    km_driven: 90000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti SX4 Vxi BSIII',
    year: 2007,
    selling_price: 120000,
    km_driven: 90000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti Ertiga VDI',
    year: 2014,
    selling_price: 500000,
    km_driven: 120000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Chevrolet Beat Dizel',
    year: 2013,
    selling_price: 165000,
    km_driven: 60000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Maruti Zen LX',
    year: 2004,
    selling_price: 95000,
    km_driven: 50000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Baleno Delta 1.2',
    year: 2018,
    selling_price: 550000,
    km_driven: 20000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Swift Vdi BSIII',
    year: 2007,
    selling_price: 100000,
    km_driven: 110000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Dördüncü veya Daha Fazla Sahibi',
  },
  {
    name: 'Tata Nano Lx BSIV',
    year: 2012,
    selling_price: 100000,
    km_driven: 50000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Toyota Innova 2.5 GX (Dizel) 8 Seater',
    year: 2012,
    selling_price: 500000,
    km_driven: 100000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Maruti Ertiga SHVS VDI',
    year: 2016,
    selling_price: 800000,
    km_driven: 70000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Hyundai Creta 1.6 CRDi SX',
    year: 2016,
    selling_price: 840000,
    km_driven: 70000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Honda Amaze S i-Vtech',
    year: 2016,
    selling_price: 490000,
    km_driven: 50000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Tata Indica Vista Aqua 1.4 TDI',
    year: 2010,
    selling_price: 125000,
    km_driven: 81000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İkinci Sahibi',
  },
  {
    name: 'Chevrolet Tavera Neo 2 LS B4 7 Str BSIII',
    year: 2012,
    selling_price: 400000,
    km_driven: 120000,
    fuel: 'Dizel',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'Üçüncü Sahibi',
  },
  {
    name: 'Chevrolet Cruze LTZ',
    year: 2015,
    selling_price: 1000000,
    km_driven: 3600,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Ford Figo Aspire 1.2 Ti-VCT Titanium Plus',
    year: 2015,
    selling_price: 530000,
    km_driven: 14272,
    fuel: 'Benzin',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Ford EcoSport 1.5 Dizel Titanium Plus BSIV',
    year: 2017,
    selling_price: 840000,
    km_driven: 49213,
    fuel: 'Dizel',
    seller_type: 'Galeri',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
  {
    name: 'Hyundai i10 Sportz 1.1L',
    year: 2015,
    selling_price: 229999,
    km_driven: 40000,
    fuel: 'Benzin',
    seller_type: 'Sahibinden',
    transmission: 'Manuel',
    owner: 'İlk Sahibi',
  },
];

function analyzeData(cars,marka,model) {
  const filtered = cars.filter(car=>{
    const splitedName = car.name.split(" ")
    if(splitedName.includes(marka) && car.year === model){
      return car
    }
  })
  console.log(filtered)
  if(filtered.length>0){
    const toplamPrice = filtered.reduce((a,b)=>a+b.selling_price,0)
    return `Model yılı ${model} olan ${marka} marka ${filtered.length} arabanın toplam piyasa değeri ${toplamPrice} TL'dir.`
    
  }else {
    return `Model yılı ${model} olan ${marka} marka araba stoklarda bulunamamıştır!`;
  }
}
console.log(analyzeData(arabaStogu, "Hyundai", 2012))